import json
from pathlib import Path

OUT = Path(__file__).parent / "test-cases"
OUT.mkdir(parents=True, exist_ok=True)


def request(method, path, body=None, query=None, auth=True, headers=None):
    merged_headers = {}
    if auth:
        merged_headers["Authorization"] = "Bearer {{global.accessToken}}"
    if headers:
        merged_headers.update(headers)
    return {
        "method": method,
        "path": path,
        "headers": merged_headers,
        "query": query or {},
        "body": body or {},
    }


def case(case_id, title, description, severity, precondition, request_message, status, checks, db=None):
    return {
        "caseId": case_id,
        "title": title,
        "description": description,
        "severity": severity,
        "precondition": precondition,
        "requestMessage": request_message,
        "expectedResponse": {"statusCode": status, "checks": checks},
        "dbExpectation": db or [],
    }


def write(filename, module, cases):
    payload = {"module": module, "basePath": "/api/v1", "testCases": cases}
    (OUT / filename).write_text(json.dumps(payload, indent=2), encoding="utf-8")


AUTH = ["User is authenticated."]

DEFECT_BODY = {
    "title": "API defect {{global.runId}}",
    "description": "Created by API test.",
    "projectId": "{{data.projects.billingCore.id}}",
    "moduleComponent": "Invoice Review",
    "environmentId": "{{data.environments.uat.id}}",
    "severityId": "{{data.severities.high.id}}",
    "priorityId": "{{data.priorities.p1.id}}",
    "assignedToUserId": "{{data.users.aishaKhan.id}}",
    "stepsHtml": "<p>Open invoice review.</p>",
    "expectedResult": "Invoice total remains stable.",
    "actualResult": "Invoice total changes.",
}


def setup_files():
    (OUT / "global.setup.json").write_text(
        json.dumps(
            {
                "purpose": "Shared runtime setup for API test execution. Only true runtime globals live here.",
                "basePath": "/api/v1",
                "login": {
                    "requestMessage": request(
                        "POST",
                        "/api/v1/auth/login",
                        {
                            "username": "{{secrets.testUsername}}",
                            "password": "{{secrets.testPassword}}",
                            "dataContext": "All",
                        },
                        auth=False,
                    ),
                    "capture": {
                        "accessToken": "$.accessToken",
                        "refreshToken": "$.refreshToken",
                        "loggedInUserId": "$.user.id",
                        "loggedInUsername": "$.user.username",
                        "activeDataContext": "$.activeDataContext",
                    },
                },
                "runtimeVariables": {
                    "runId": "Generated by framework for each run.",
                    "accessToken": "Captured from login response.",
                    "refreshToken": "Captured from login response.",
                    "loggedInUserId": "Captured from login response.",
                },
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (OUT / "test-data.catalog.json").write_text(
        json.dumps(
            {
                "purpose": "Semantic selectors for data lookup. Framework resolves IDs from the current API/DB before execution.",
                "projects": {
                    "billingCore": {"selector": {"projectName": "Billing Core", "isActive": True}},
                    "claimsPortal": {"selector": {"projectName": "Claims Portal", "isActive": True}},
                    "inactiveProject": {"selector": {"isActive": False}},
                },
                "environments": {
                    "dev": {"selector": {"environmentName": "DEV", "environmentScope": "Test", "isActive": True}},
                    "sit": {"selector": {"environmentName": "SIT", "environmentScope": "Test", "isActive": True}},
                    "uat": {"selector": {"environmentName": "UAT", "environmentScope": "Test", "isActive": True}},
                    "prod": {"selector": {"environmentName": "PROD", "environmentScope": "Prod", "isActive": True}},
                },
                "severities": {
                    "critical": {"selector": {"name": "Critical"}},
                    "high": {"selector": {"name": "High"}},
                    "medium": {"selector": {"name": "Medium"}},
                    "low": {"selector": {"name": "Low"}},
                },
                "priorities": {
                    "p1": {"selector": {"name": "P1"}},
                    "p2": {"selector": {"name": "P2"}},
                    "p3": {"selector": {"name": "P3"}},
                    "p4": {"selector": {"name": "P4"}},
                },
                "users": {
                    "aishaKhan": {"selector": {"username": "aisha.khan", "isActive": True}},
                    "qaUser": {"selector": {"username": "qa.user", "isActive": True}},
                },
                "releases": {"billingRelease": {"selector": {"project": "billingCore", "isActive": True}}},
                "workflowStatuses": {
                    "assigned": {"value": "Assigned"},
                    "inProgress": {"value": "InProgress"},
                    "fixed": {"value": "Fixed"},
                    "closed": {"value": "Closed"},
                    "rejected": {"value": "Rejected"},
                },
            },
            indent=2,
        ),
        encoding="utf-8",
    )


def auth_cases():
    return [
        case("AUTH-API-001", "Login succeeds with valid user", "Verify valid credentials return a bearer token and user profile context.", "Critical", ["Seeded active user credentials are available."], request("POST", "/api/v1/auth/login", {"username": "{{secrets.testUsername}}", "password": "{{secrets.testPassword}}", "dataContext": "Test"}, auth=False), 200, ["Response contains accessToken.", "Response contains refreshToken.", "Response user.username matches request.", "activeDataContext is Test."]),
        case("AUTH-API-002", "Login rejects missing username", "Verify login fails when username is absent in the current live API.", "High", [], request("POST", "/api/v1/auth/login", {"password": "{{secrets.testPassword}}"}, auth=False), 401, ["Response error.code is invalid_credentials.", "No token is returned."]),
        case("AUTH-API-003", "Login rejects missing password", "Verify login requires a password for an active username.", "Critical", [], request("POST", "/api/v1/auth/login", {"username": "{{secrets.testUsername}}"}, auth=False), 401, ["Response error.code is invalid_credentials.", "No token is returned."]),
        case("AUTH-API-004", "Login rejects wrong password", "Verify login validates the password for an active username.", "Critical", [], request("POST", "/api/v1/auth/login", {"username": "{{secrets.testUsername}}", "password": "wrong-password"}, auth=False), 401, ["Response error.code is invalid_credentials.", "No token is returned."]),
        case("AUTH-API-005", "Refresh token succeeds", "Verify refresh endpoint returns a new access token for a valid refresh token.", "High", ["A valid refresh token is available from login."], request("POST", "/api/v1/auth/refresh", {"refreshToken": "{{global.refreshToken}}"}, auth=False), 200, ["Response contains accessToken.", "Response contains refreshToken."]),
        case("AUTH-API-006", "Refresh token rejects empty token", "Verify refresh endpoint rejects requests without a refresh token.", "High", [], request("POST", "/api/v1/auth/refresh", {}, auth=False), 401, ["Response error.code is invalid_refresh_token.", "No token is returned."]),
        case("AUTH-API-007", "Current user succeeds", "Verify authenticated user profile can be read.", "High", AUTH, request("GET", "/api/v1/auth/me"), 200, ["Response contains user id.", "Response contains availableDataContexts."]),
        case("AUTH-API-008", "Current user without token is rejected", "Verify current user endpoint requires a bearer token.", "Critical", [], request("GET", "/api/v1/auth/me", auth=False), 401, ["Response error.code is unauthorized.", "No user profile is returned."]),
        case("AUTH-API-009", "Update own profile succeeds", "Verify user can update own email profile field.", "Medium", AUTH, request("PATCH", "/api/v1/auth/profile", {"email": "qa.profile.{{global.runId}}@example.com"}), 200, ["Response email matches request."], ["app_users current user email is updated."]),
        case("AUTH-API-010", "Update own profile currently accepts non-email string", "Document current live behavior where profile email format is not yet validated.", "High", AUTH, request("PATCH", "/api/v1/auth/profile", {"email": "not-an-email-{{global.runId}}"}), 200, ["Response email matches request value.", "This is a validation gap to harden later."], ["app_users current user email is updated per current behavior."]),
        case("AUTH-API-011", "Change own password succeeds", "Verify password change accepts previous, new, and confirm password.", "High", AUTH, request("POST", "/api/v1/auth/password", {"previousPassword": "{{secrets.testPassword}}", "newPassword": "Welcome1234", "confirmPassword": "Welcome1234"}), 204, ["Empty response body is returned."], ["user_password_events self_change event is created."]),
        case("AUTH-API-012", "Change own password rejects mismatched confirmation", "Verify password change rejects different new and confirm values.", "High", AUTH, request("POST", "/api/v1/auth/password", {"previousPassword": "{{secrets.testPassword}}", "newPassword": "Welcome1234", "confirmPassword": "Welcome5678"}), 400, ["Response indicates validation error."], ["Password is not changed."]),
        case("AUTH-API-013", "Login without context uses user default", "Verify login uses app_users.default_data_context when dataContext is omitted.", "High", ["A seeded or disposable user exists with defaultDataContext set to Prod or All."], request("POST", "/api/v1/auth/login", {"username": "{{secrets.contextUsername}}", "password": "{{secrets.contextPassword}}"}, auth=False), 200, ["Response activeDataContext matches app_users.default_data_context.", "Response user.defaultDataContext matches app_users.default_data_context."], ["app_users.default_data_context is not modified by login."]),
        case("AUTH-API-014", "Login context overrides user default for session", "Verify explicit login dataContext overrides the saved user default for the returned session context.", "High", ["A seeded or disposable user exists with defaultDataContext different from the requested dataContext."], request("POST", "/api/v1/auth/login", {"username": "{{secrets.contextUsername}}", "password": "{{secrets.contextPassword}}", "dataContext": "All"}, auth=False), 200, ["Response activeDataContext is All.", "Response user.defaultDataContext still matches app_users.default_data_context."], ["app_users.default_data_context is not modified by login override."]),
    ]


def users_cases():
    return [
        case("USERS-API-001", "List users succeeds", "Verify users can be listed with pagination.", "High", AUTH, request("GET", "/api/v1/users", query={"page": 1, "pageSize": 10}), 200, ["Response contains items array.", "Response contains pagination."]),
        case("USERS-API-002", "List users filters active users", "Verify isActive filter limits users by active flag.", "Medium", AUTH, request("GET", "/api/v1/users", query={"isActive": "true"}), 200, ["Every returned user has isActive true."]),
        case("USERS-API-003", "Search users succeeds", "Verify search filters users by name, email, or username.", "Medium", AUTH, request("GET", "/api/v1/users", query={"search": "aisha"}), 200, ["Returned users match search criteria when data exists."]),
        case("USERS-API-004", "Create user succeeds", "Verify valid user creation including password confirmation.", "High", AUTH, request("POST", "/api/v1/users", {"name": "API User {{global.runId}}", "email": "api.user.{{global.runId}}@example.com", "username": "api.user.{{global.runId}}", "password": "Welcome123", "confirmPassword": "Welcome123", "isActive": True, "defaultDataContext": "Test"}), 201, ["Response contains id.", "Response username matches request.", "Response defaultDataContext is Test."], ["app_users record is created."]),
        case("USERS-API-005", "Create user rejects duplicate username", "Verify duplicate username is rejected.", "High", ["User is authenticated.", "A user exists with username aisha.khan."], request("POST", "/api/v1/users", {"name": "Duplicate User", "email": "dup.{{global.runId}}@example.com", "username": "aisha.khan", "password": "Welcome123", "confirmPassword": "Welcome123", "isActive": True}), 400, ["Response indicates username already exists."], ["No user is created."]),
        case("USERS-API-006", "Create user rejects password mismatch", "Verify user creation rejects mismatched password confirmation.", "High", AUTH, request("POST", "/api/v1/users", {"name": "Bad Password User", "email": "bad.pass.{{global.runId}}@example.com", "username": "bad.pass.{{global.runId}}", "password": "Welcome123", "confirmPassword": "Different123", "isActive": True}), 400, ["Response indicates passwords do not match."], ["No user is created."]),
        case("USERS-API-007", "Update user succeeds", "Verify an existing user can be updated.", "High", ["User is authenticated.", "A disposable user exists for update."], request("PATCH", "/api/v1/users/{{createdUserId}}", {"name": "Updated API User {{global.runId}}", "isActive": False}), 200, ["Response name matches request.", "Response isActive is false."], ["app_users record is updated.", "updated_by_user_id is current user."]),
        case("USERS-API-008", "Update user rejects duplicate email", "Verify user update rejects email already used by another user.", "High", ["User is authenticated.", "A disposable user exists.", "Another user exists with email from test data."], request("PATCH", "/api/v1/users/{{createdUserId}}", {"email": "{{data.users.aishaKhan.email}}"}), 400, ["Response indicates email already exists."], ["User email remains unchanged."]),
        case("USERS-API-009", "Update user not found", "Verify updating a missing user returns not found.", "Medium", AUTH, request("PATCH", "/api/v1/users/{{missingUserId}}", {"name": "Missing"}), 404, ["Response indicates user not found."]),
        case("USERS-API-010", "Reset user password succeeds", "Verify password reset endpoint accepts new and confirm password.", "High", ["User is authenticated.", "A disposable active user exists."], request("POST", "/api/v1/users/{{createdUserId}}/password", {"newPassword": "Welcome1234", "confirmPassword": "Welcome1234"}), 204, ["Empty response body is returned."], ["user_password_events reset event is created."]),
        case("USERS-API-011", "Reset user password rejects mismatch", "Verify reset password rejects different values.", "High", ["User is authenticated.", "A disposable user exists."], request("POST", "/api/v1/users/{{createdUserId}}/password", {"newPassword": "Welcome1234", "confirmPassword": "Different123"}), 400, ["Response indicates passwords do not match."], ["Password is not changed."]),
        case("USERS-API-012", "Users list currently accepts missing bearer token", "Document current live proof-layer behavior where missing bearer token still allows user listing.", "Critical", [], request("GET", "/api/v1/users", auth=False), 200, ["Response contains items array.", "This is a known hardening gap before production auth."]),
    ]


def simple_master_cases(prefix, module, base_path, name_field, duplicate_value, body, update_body, missing_id_var):
    lower = module.lower()
    return [
        case(f"{prefix}-API-001", f"List {lower} succeeds", f"Verify {lower} can be listed.", "High", AUTH, request("GET", base_path), 200, ["Response contains items array."]),
        case(f"{prefix}-API-002", f"List {lower} filters active flag", f"Verify {lower} list can filter by active status.", "Medium", AUTH, request("GET", base_path, query={"isActive": "true"}), 200, ["Every returned record has isActive true."]),
        case(f"{prefix}-API-003", f"Search {lower} succeeds", f"Verify search filters {lower}.", "Medium", AUTH, request("GET", base_path, query={"search": duplicate_value.split()[0]}), 200, ["Returned records match search criteria when data exists."]),
        case(f"{prefix}-API-004", f"Create {lower} succeeds", f"Verify a {lower} record can be created.", "High", AUTH, request("POST", base_path, body), 201, ["Response contains id.", f"Response {name_field} matches request."], [f"{lower} record is created."]),
        case(f"{prefix}-API-005", f"Create {lower} rejects duplicate name", f"Verify duplicate {lower} name is rejected.", "High", AUTH, request("POST", base_path, {**body, name_field: duplicate_value}), 400, ["Response indicates name already exists."], [f"No {lower} record is created."]),
        case(f"{prefix}-API-006", f"Create {lower} rejects missing name", f"Verify {name_field} is mandatory.", "Medium", AUTH, request("POST", base_path, {k: v for k, v in body.items() if k != name_field}), 400, ["Response indicates validation error."]),
        case(f"{prefix}-API-007", f"Update {lower} succeeds", f"Verify {lower} can be updated.", "High", ["User is authenticated.", f"A disposable {lower} record exists."], request("PATCH", f"{base_path}/{{{{created{module[:-1]}Id}}}}", update_body), 200, [f"Response {name_field} or status matches request."], [f"{lower} record is updated."]),
        case(f"{prefix}-API-008", f"Update {lower} rejects duplicate name", f"Verify {lower} update prevents duplicate name.", "High", ["User is authenticated.", f"A disposable {lower} record exists."], request("PATCH", f"{base_path}/{{{{created{module[:-1]}Id}}}}", {name_field: duplicate_value}), 400, ["Response indicates name already exists."], [f"{lower} record remains unchanged."]),
        case(f"{prefix}-API-009", f"Update {lower} not found", f"Verify updating a missing {lower} returns not found.", "Medium", AUTH, request("PATCH", f"{base_path}/{{{{{missing_id_var}}}}}", update_body), 404, [f"Response indicates {lower} not found."]),
    ]


def projects_cases():
    return simple_master_cases("PROJECTS", "Projects", "/api/v1/projects", "projectName", "Billing Core", {"projectName": "API Project {{global.runId}}", "description": "Created by API test.", "isActive": True}, {"projectName": "API Project Updated {{global.runId}}", "description": "Updated by API test.", "isActive": False}, "missingProjectId")


def environments_cases():
    cases = simple_master_cases("ENV", "Environments", "/api/v1/environments", "environmentName", "UAT", {"environmentName": "QA-SANDBOX-{{global.runId}}", "description": "API test environment.", "isActive": True, "sortOrder": 20}, {"environmentName": "QA-SANDBOX-UPDATED-{{global.runId}}", "description": "Updated.", "isActive": False, "sortOrder": 21}, "missingEnvironmentId")
    cases.insert(1, case("ENV-API-002A", "List environments filters Test scope", "Verify scope filter returns only Test environments.", "Medium", AUTH, request("GET", "/api/v1/environments", query={"scope": "Test"}), 200, ["Every returned environment has environmentScope Test."]))
    cases.insert(4, case("ENV-API-004A", "Create Prod environment succeeds by inference", "Verify production-like names are scoped as Prod by backend inference.", "High", AUTH, request("POST", "/api/v1/environments", {"environmentName": "Production", "description": "Production alias test.", "isActive": True, "sortOrder": 30}), 201, ["Response environmentScope is Prod."], ["environments record is created with Prod scope."]))
    return renumber(cases, "ENV")


def releases_cases():
    return [
        case("RELEASES-API-001", "List releases succeeds", "Verify releases can be listed.", "Medium", AUTH, request("GET", "/api/v1/releases"), 200, ["Response contains items array."]),
        case("RELEASES-API-002", "List releases filters by project", "Verify release list can be filtered by project.", "Medium", AUTH, request("GET", "/api/v1/releases", query={"projectId": "{{data.projects.billingCore.id}}"}), 200, ["Every returned release belongs to Billing Core."]),
        case("RELEASES-API-003", "Create release succeeds", "Verify release can be created for a project.", "High", AUTH, request("POST", "/api/v1/releases", {"projectId": "{{data.projects.billingCore.id}}", "releaseVersion": "API-REL-{{global.runId}}", "plannedDeploymentDate": "2026-06-01", "actualDeploymentDate": None, "isActive": True}), 201, ["Response contains id.", "Response releaseVersion matches request."], ["releases record is created."]),
        case("RELEASES-API-004", "Create release rejects missing project", "Verify projectId is required.", "Medium", AUTH, request("POST", "/api/v1/releases", {"releaseVersion": "API-REL-NO-PROJECT", "isActive": True}), 400, ["Response indicates validation error."]),
        case("RELEASES-API-005", "Create release rejects invalid project", "Verify release cannot be created for a missing project.", "High", AUTH, request("POST", "/api/v1/releases", {"projectId": "{{missingProjectId}}", "releaseVersion": "API-REL-MISSING-PROJECT", "isActive": True}), 404, ["Response indicates project not found."], ["No release is created."]),
        case("RELEASES-API-006", "Create release rejects duplicate project version", "Verify duplicate release version per project is rejected.", "High", ["User is authenticated.", "A release exists for Billing Core."], request("POST", "/api/v1/releases", {"projectId": "{{data.projects.billingCore.id}}", "releaseVersion": "{{existingReleaseVersion}}", "isActive": True}), 400, ["Response indicates release version already exists."]),
        case("RELEASES-API-007", "Update release succeeds", "Verify release can be updated.", "Medium", ["User is authenticated.", "A disposable release exists."], request("PATCH", "/api/v1/releases/{{createdReleaseId}}", {"actualDeploymentDate": "2026-06-05", "isActive": False}), 200, ["Response actualDeploymentDate matches request.", "Response isActive is false."], ["releases record is updated."]),
        case("RELEASES-API-008", "Update release rejects invalid project", "Verify release update rejects missing projectId.", "Medium", ["User is authenticated.", "A disposable release exists."], request("PATCH", "/api/v1/releases/{{createdReleaseId}}", {"projectId": "{{missingProjectId}}"}), 404, ["Response indicates project not found."]),
        case("RELEASES-API-009", "Update release not found", "Verify updating a missing release returns not found.", "Medium", AUTH, request("PATCH", "/api/v1/releases/{{missingReleaseId}}", {"isActive": False}), 404, ["Response indicates release not found."]),
    ]


def workflow_cases():
    return [
        case("WORKFLOW-API-001", "Get workflow succeeds", "Verify active workflow and transitions are returned.", "Critical", AUTH, request("GET", "/api/v1/workflow"), 200, ["Response contains diagram.", "Response contains transitions array."]),
        case("WORKFLOW-API-002", "List transitions from valid status succeeds", "Verify allowed statuses can be queried for a workflow status.", "High", AUTH, request("GET", "/api/v1/workflow/transitions", query={"fromStatus": "InProgress"}), 200, ["Response currentStatus is InProgress.", "Response contains allowedStatuses."]),
        case("WORKFLOW-API-003", "List transitions rejects missing fromStatus", "Verify fromStatus query is required.", "Medium", AUTH, request("GET", "/api/v1/workflow/transitions"), 400, ["Response indicates fromStatus is required."]),
        case("WORKFLOW-API-004", "List transitions rejects unknown status", "Verify unknown workflow status returns validation error.", "Medium", AUTH, request("GET", "/api/v1/workflow/transitions", query={"fromStatus": "UnknownStatus"}), 400, ["Response indicates status is not in active workflow."]),
        case("WORKFLOW-API-005", "Save workflow succeeds", "Verify workflow save creates a new active workflow version and transitions.", "Critical", AUTH, request("POST", "/api/v1/workflow", {"workflowName": "API Workflow {{global.runId}}", "diagram": {"nodes": [{"id": "n1", "type": "process", "label": "Assigned", "position": {"x": 100, "y": 100}}, {"id": "n2", "type": "process", "label": "InProgress", "position": {"x": 300, "y": 100}}], "edges": [{"id": "e1", "source": "n1", "target": "n2"}]}}), 200, ["Response versionNo is incremented.", "Response transitions include Assigned to InProgress."], ["workflow_definitions new active version is created.", "workflow_transitions are regenerated from diagram."]),
        case("WORKFLOW-API-006", "Save workflow rejects empty diagram", "Verify empty workflow diagrams are rejected before persistence.", "High", AUTH, request("POST", "/api/v1/workflow", {"workflowName": "Empty Workflow {{global.runId}}", "diagram": {"nodes": [], "edges": []}}), 400, ["Response error.code is validation_error.", "No active workflow version is created."]),
        case("WORKFLOW-API-007", "Save workflow rejects edge with missing node", "Verify invalid edge references cannot be saved.", "High", AUTH, request("POST", "/api/v1/workflow", {"workflowName": "Invalid Edge {{global.runId}}", "diagram": {"nodes": [{"id": "n1", "type": "process", "label": "Assigned", "position": {"x": 100, "y": 100}}], "edges": [{"id": "e1", "source": "n1", "target": "missing"}]}}), 400, ["Response error.code is validation_error.", "Invalid edge is not converted into an active transition."]),
        case("WORKFLOW-API-008", "Workflow get requires bearer token", "Verify active workflow cannot be read without authentication.", "Critical", [], request("GET", "/api/v1/workflow", auth=False), 401, ["Response error.code is unauthorized."]),
        case("WORKFLOW-API-009", "Transition lookup supports terminal status", "Verify a status with no outgoing transition returns empty allowedStatuses.", "Medium", AUTH, request("GET", "/api/v1/workflow/transitions", query={"fromStatus": "Rejected"}), 200, ["Response allowedStatuses is empty when Rejected has no next status."]),
        case("WORKFLOW-API-010", "Workflow save preserves diagram JSON", "Verify saved diagram is returned in workflow response.", "Medium", AUTH, request("POST", "/api/v1/workflow", {"workflowName": "Diagram Echo {{global.runId}}", "diagram": {"nodes": [{"id": "n1", "type": "process", "label": "Assigned", "position": {"x": 10, "y": 20}}], "edges": []}}), 200, ["Response diagram contains node n1."]),
        case("WORKFLOW-API-011", "Workflow save requires bearer token", "Verify workflow save cannot happen without authentication.", "Critical", [], request("POST", "/api/v1/workflow", {"workflowName": "Unauthorized {{global.runId}}", "diagram": {"nodes": [{"id": "n1", "type": "process", "label": "Assigned", "position": {"x": 10, "y": 20}}], "edges": []}}, auth=False), 401, ["Response error.code is unauthorized."]),
    ]


def defects_cases():
    return [
        case("DEFECT-API-001", "List defects succeeds", "Verify defect list returns paginated defects.", "High", AUTH, request("GET", "/api/v1/defects", query={"page": 1, "pageSize": 10}), 200, ["Response contains items array.", "Response contains pagination."]),
        case("DEFECT-API-002", "List defects respects Test context", "Verify X-Data-Context Test returns Test scoped defects.", "High", AUTH, request("GET", "/api/v1/defects", headers={"X-Data-Context": "Test"}), 200, ["Returned defects belong to Test environments."]),
        case("DEFECT-API-003", "List defects respects Prod context", "Verify X-Data-Context Prod returns production defects.", "High", AUTH, request("GET", "/api/v1/defects", headers={"X-Data-Context": "Prod"}), 200, ["Returned defects belong to Prod environments."]),
        case("DEFECT-API-004", "List defects filters by project", "Verify projectId filter returns only selected project defects.", "Medium", AUTH, request("GET", "/api/v1/defects", query={"projectId": "{{data.projects.billingCore.id}}"}), 200, ["Every returned defect belongs to Billing Core."]),
        case("DEFECT-API-005", "Create defect succeeds", "Verify valid defect creation.", "Critical", AUTH, request("POST", "/api/v1/defects", DEFECT_BODY, query={"forceCreate": "true"}), 201, ["Response contains id.", "Response contains defectKey.", "Response currentStatus is assigned by workflow."], ["defects record is created.", "defect_created history event is created."]),
        case("DEFECT-API-006", "Create defect warns for duplicate same project title", "Verify same normalized title in same project returns advisory warning.", "High", ["User is authenticated.", "A baseline defect exists in Billing Core with matching title."], request("POST", "/api/v1/defects", {**DEFECT_BODY, "title": "Duplicate billing defect {{global.runId}}", "environmentId": "{{data.environments.prod.id}}", "moduleComponent": "Different Module"}, query={"forceCreate": "false"}), 409, ["Response error.code is possible_duplicate_defect.", "Response contains duplicateCandidates."], ["Second defect is not created."]),
        case("DEFECT-API-007", "Create same title in different project succeeds", "Verify duplicate warning is project-scoped only.", "Medium", ["User is authenticated.", "A baseline defect exists in Billing Core with same title."], request("POST", "/api/v1/defects", {**DEFECT_BODY, "title": "Cross project duplicate {{global.runId}}", "projectId": "{{data.projects.claimsPortal.id}}"}, query={"forceCreate": "false"}), 201, ["Response is created.", "No duplicate advisory is returned."], ["defects record is created in Claims Portal."]),
        case("DEFECT-API-008", "Create defect rejects missing expected result", "Verify expectedResult is mandatory.", "High", AUTH, request("POST", "/api/v1/defects", {k: v for k, v in DEFECT_BODY.items() if k != "expectedResult"}), 400, ["Response indicates validation error."], ["No defect is created."]),
        case("DEFECT-API-009", "Create defect rejects invalid project", "Verify missing project ID is rejected.", "High", AUTH, request("POST", "/api/v1/defects", {**DEFECT_BODY, "projectId": "{{missingProjectId}}"}), 400, ["Response indicates data integrity or validation error."], ["No defect is created."]),
        case("DEFECT-API-010", "Get defect detail succeeds", "Verify defect detail includes child sections.", "High", ["User is authenticated.", "A defect exists."], request("GET", "/api/v1/defects/{{createdDefectId}}"), 200, ["Response contains description.", "Response contains allowedNextStatuses.", "Response contains attachments, inlineAssets, and comments arrays."]),
        case("DEFECT-API-011", "Get defect not found", "Verify missing defect returns not found.", "Medium", AUTH, request("GET", "/api/v1/defects/{{missingDefectId}}"), 404, ["Response indicates defect not found."]),
        case("DEFECT-API-012", "Update defect valid status succeeds", "Verify status can move through allowed workflow transition.", "Critical", ["User is authenticated.", "A defect exists in Assigned status."], request("PATCH", "/api/v1/defects/{{createdDefectId}}", {"currentStatus": "InProgress"}), 200, ["Response currentStatus is InProgress."], ["defects current_status is updated.", "status_changed history event is created."]),
        case("DEFECT-API-013", "Update defect invalid status transition rejected", "Verify workflow prevents invalid status jump.", "Critical", ["User is authenticated.", "A defect exists in Assigned status."], request("PATCH", "/api/v1/defects/{{createdDefectId}}", {"currentStatus": "Fixed"}), 400, ["Response error.code is invalid_status_transition."], ["Defect status remains unchanged."]),
        case("DEFECT-API-014", "Update defect to Fixed requires release and fix date", "Verify fixed status cannot be saved without release/date context.", "Critical", ["User is authenticated.", "A defect exists in InProgress status."], request("PATCH", "/api/v1/defects/{{createdDefectId}}", {"currentStatus": "Fixed"}), 400, ["Response error.code is validation_error.", "Response indicates Release Version or Fix Date is required."], ["Defect status remains unchanged."]),
        case("DEFECT-API-015", "Update defect to Closed requires closure date", "Verify closed status cannot be saved without closure date.", "Critical", ["User is authenticated.", "A defect exists where Closed is an allowed next status."], request("PATCH", "/api/v1/defects/{{createdDefectId}}", {"currentStatus": "Closed"}), 400, ["Response error.code is validation_error.", "Response indicates Closure Date is required."], ["Defect status remains unchanged."]),
        case("DEFECT-API-016", "Delete defect soft deletes record", "Verify delete marks defect as deleted.", "High", ["User is authenticated.", "A disposable defect exists."], request("DELETE", "/api/v1/defects/{{createdDefectId}}"), 204, ["Empty response body is returned."], ["defects is_deleted is true.", "field_updated history event is created."]),
        case("DEFECT-API-017", "Defects list requires bearer token", "Verify defect list is protected by bearer authentication.", "Critical", [], request("GET", "/api/v1/defects", auth=False), 401, ["Response error.code is unauthorized."]),
    ]


def attachments_cases():
    body = {
        "filename": "invoice-error-{{global.runId}}.png",
        "contentType": "image/png",
        "fileSizeBytes": 68,
        "contentDataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII="
    }
    return [
        case("ATTACH-API-001", "List attachments succeeds", "Verify attachments can be listed for a defect.", "Medium", ["User is authenticated.", "A defect exists."], request("GET", "/api/v1/defects/{{createdDefectId}}/attachments"), 200, ["Response contains items array."]),
        case("ATTACH-API-002", "Upload attachment content succeeds", "Verify JSON upload content creates a database record and matching stored file.", "High", ["User is authenticated.", "A defect exists."], request("POST", "/api/v1/defects/{{createdDefectId}}/attachments", body), 201, ["Response contains id.", "Response originalFilename matches request.", "Response contentUrl exists."], ["defect_attachments record is created.", "storage_key points to a physical file.", "attachment_uploaded history event is created."]),
        case("ATTACH-API-003", "Upload attachment rejects unsupported extension", "Verify unsupported attachment extensions are rejected.", "High", ["User is authenticated.", "A defect exists."], request("POST", "/api/v1/defects/{{createdDefectId}}/attachments", {"filename": "defects-{{global.runId}}.csv", "contentType": "text/csv", "fileSizeBytes": 100, "contentDataUrl": "data:text/csv;base64,YSxi"}), 400, ["Response error.code is validation_error.", "Response explains allowed file types."], ["No attachment is created."]),
        case("ATTACH-API-004", "Upload attachment rejects invalid defect", "Verify missing defect ID is handled before metadata insert.", "High", AUTH, request("POST", "/api/v1/defects/{{missingDefectId}}/attachments", body), 404, ["Response indicates defect not found."], ["No attachment is created."]),
        case("ATTACH-API-005", "Delete attachment succeeds", "Verify attachment delete is soft delete.", "High", ["User is authenticated.", "A defect attachment exists."], request("DELETE", "/api/v1/defects/{{createdDefectId}}/attachments/{{createdAttachmentId}}"), 204, ["Empty response body is returned."], ["defect_attachments is_deleted is true.", "attachment_deleted history event is created."]),
        case("ATTACH-API-006", "Delete attachment not found", "Verify missing attachment returns not found.", "Medium", ["User is authenticated.", "A defect exists."], request("DELETE", "/api/v1/defects/{{createdDefectId}}/attachments/{{missingAttachmentId}}"), 404, ["Response indicates attachment not found."]),
        case("ATTACH-API-007", "Get attachment content succeeds", "Verify current API streams the stored attachment bytes.", "Medium", ["User is authenticated.", "An attachment exists.", "The attachment storage_key points to a physical file."], request("GET", "/api/v1/defects/{{createdDefectId}}/attachments/{{createdAttachmentId}}/content"), 200, ["Response bytes match the uploaded attachment.", "Content-Disposition is an attachment download."]),
        case("ATTACH-API-008", "Get attachment content not found", "Verify missing attachment content returns not found.", "Medium", ["User is authenticated.", "A defect exists."], request("GET", "/api/v1/defects/{{createdDefectId}}/attachments/{{missingAttachmentId}}/content"), 404, ["Response indicates attachment not found."]),
        case("ATTACH-API-009", "Upload attachment rejects empty body", "Verify attachment upload requires filename and file content.", "High", ["User is authenticated.", "A defect exists."], request("POST", "/api/v1/defects/{{createdDefectId}}/attachments", {}), 400, ["Response error.code is validation_error.", "Response identifies missing filename or file content."], ["No attachment is created."]),
        case("ATTACH-API-010", "Attachment list requires bearer token", "Verify attachment list is protected by bearer authentication.", "Critical", ["A defect exists."], request("GET", "/api/v1/defects/{{createdDefectId}}/attachments", auth=False), 401, ["Response error.code is unauthorized."]),
    ]


def inline_cases():
    inline_body = {
        "filename": "step-{{global.runId}}.png",
        "contentType": "image/png",
        "fileSizeBytes": 68,
        "widthPx": 800,
        "heightPx": 600,
        "contentDataUrl": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII="
    }
    return [
        case("INLINE-API-001", "Upload inline asset succeeds", "Verify inline Steps image content can be created with a matching stored file.", "High", ["User is authenticated.", "A defect exists."], request("POST", "/api/v1/defects/{{createdDefectId}}/inline-assets", inline_body), 201, ["Response contains id.", "Response contentUrl exists.", "Response widthPx is 800."], ["defect_inline_assets record is created.", "storage_key points to a physical file.", "inline_asset_added history event is created."]),
        case("INLINE-API-002", "Upload inline asset rejects non-image content type", "Verify inline assets are limited to pasted image content.", "High", ["User is authenticated.", "A defect exists."], request("POST", "/api/v1/defects/{{createdDefectId}}/inline-assets", {"filename": "bad.txt", "contentType": "text/plain", "fileSizeBytes": 100, "widthPx": 100, "heightPx": 100, "contentDataUrl": "data:text/plain;base64,dGVzdA=="}), 400, ["Response error.code is validation_error.", "Response states inline assets must be images."], ["No inline asset is created."]),
        case("INLINE-API-003", "Upload inline asset rejects invalid defect", "Verify invalid defect ID is handled.", "High", AUTH, request("POST", "/api/v1/defects/{{missingDefectId}}/inline-assets", inline_body), 404, ["Response indicates defect not found."]),
        case("INLINE-API-004", "Update inline asset dimensions succeeds", "Verify asset display dimensions can be updated.", "Medium", ["User is authenticated.", "An inline asset exists."], request("PATCH", "/api/v1/defects/{{createdDefectId}}/inline-assets/{{createdInlineAssetId}}", {"widthPx": 1024, "heightPx": 768}), 200, ["Response widthPx is 1024.", "Response heightPx is 768."], ["defect_inline_assets dimensions are updated."]),
        case("INLINE-API-005", "Update inline asset rejects zero width", "Verify inline asset dimensions must be positive values.", "High", ["User is authenticated.", "An inline asset exists."], request("PATCH", "/api/v1/defects/{{createdDefectId}}/inline-assets/{{createdInlineAssetId}}", {"widthPx": 0}), 400, ["Response error.code is validation_error."]),
        case("INLINE-API-006", "Delete inline asset succeeds", "Verify inline asset delete is soft delete.", "High", ["User is authenticated.", "An inline asset exists."], request("DELETE", "/api/v1/defects/{{createdDefectId}}/inline-assets/{{createdInlineAssetId}}"), 204, ["Empty response body is returned."], ["defect_inline_assets is_deleted is true."]),
        case("INLINE-API-007", "Delete inline asset not found", "Verify missing inline asset returns not found.", "Medium", ["User is authenticated.", "A defect exists."], request("DELETE", "/api/v1/defects/{{createdDefectId}}/inline-assets/{{missingInlineAssetId}}"), 404, ["Response indicates inline asset not found."]),
        case("INLINE-API-008", "Get inline asset content succeeds", "Verify current API streams the stored inline image bytes.", "Medium", ["User is authenticated.", "An inline asset exists.", "The inline storage_key points to a physical file."], request("GET", "/api/v1/defects/{{createdDefectId}}/inline-assets/{{createdInlineAssetId}}/content"), 200, ["Response bytes match the uploaded image.", "Content-Type remains image/png or image/jpeg."]),
        case("INLINE-API-009", "Inline asset upload requires bearer token", "Verify inline asset upload is protected by bearer authentication.", "Critical", ["A defect exists."], request("POST", "/api/v1/defects/{{createdDefectId}}/inline-assets", {"filename": "step.png", "contentType": "image/png", "fileSizeBytes": 100, "widthPx": 100, "heightPx": 100}, auth=False), 401, ["Response error.code is unauthorized."]),
    ]


def comments_cases():
    return [
        case("COMMENT-API-001", "List comments succeeds", "Verify defect comments can be listed.", "Medium", ["User is authenticated.", "A defect exists."], request("GET", "/api/v1/defects/{{createdDefectId}}/comments"), 200, ["Response contains items array."]),
        case("COMMENT-API-002", "Add comment succeeds", "Verify a comment can be added to a defect.", "High", ["User is authenticated.", "A defect exists."], request("POST", "/api/v1/defects/{{createdDefectId}}/comments", {"commentText": "API comment {{global.runId}}"}), 201, ["Response contains id.", "Response commentText matches request.", "Response createdBy matches logged-in user."], ["defect_comments record is created.", "comment_added history event is created."]),
        case("COMMENT-API-003", "Add comment rejects empty text", "Verify comment creation requires readable text.", "High", ["User is authenticated.", "A defect exists."], request("POST", "/api/v1/defects/{{createdDefectId}}/comments", {"commentText": ""}), 400, ["Response error.code is validation_error.", "Response identifies Comment as required."], ["No comment is created."]),
        case("COMMENT-API-004", "Add comment invalid defect", "Verify adding comment to missing defect is handled.", "High", AUTH, request("POST", "/api/v1/defects/{{missingDefectId}}/comments", {"commentText": "Missing defect comment"}), 404, ["Response indicates defect not found."], ["No comment is created."]),
        case("COMMENT-API-005", "Update comment succeeds", "Verify existing comment can be updated.", "Medium", ["User is authenticated.", "A comment exists."], request("PATCH", "/api/v1/defects/{{createdDefectId}}/comments/{{createdCommentId}}", {"commentText": "Updated API comment {{global.runId}}"}), 200, ["Response commentText matches request."], ["defect_comments record is updated.", "comment_updated history event is created."]),
        case("COMMENT-API-006", "Update comment rejects empty text", "Verify comment update requires readable text.", "High", ["User is authenticated.", "A comment exists."], request("PATCH", "/api/v1/defects/{{createdDefectId}}/comments/{{createdCommentId}}", {"commentText": ""}), 400, ["Response error.code is validation_error.", "Response identifies Comment as required."]),
        case("COMMENT-API-007", "Update comment not found", "Verify updating missing comment returns not found.", "Medium", ["User is authenticated.", "A defect exists."], request("PATCH", "/api/v1/defects/{{createdDefectId}}/comments/{{missingCommentId}}", {"commentText": "Missing"}), 404, ["Response indicates comment not found."]),
        case("COMMENT-API-008", "Delete comment succeeds", "Verify comment delete is soft delete.", "High", ["User is authenticated.", "A comment exists."], request("DELETE", "/api/v1/defects/{{createdDefectId}}/comments/{{createdCommentId}}"), 204, ["Empty response body is returned."], ["defect_comments is_deleted is true.", "comment_deleted history event is created."]),
        case("COMMENT-API-009", "Delete comment not found", "Verify deleting missing comment returns not found.", "Medium", ["User is authenticated.", "A defect exists."], request("DELETE", "/api/v1/defects/{{createdDefectId}}/comments/{{missingCommentId}}"), 404, ["Response indicates comment not found."]),
        case("COMMENT-API-010", "Comments list requires bearer token", "Verify comments list is protected by bearer authentication.", "Critical", ["A defect exists."], request("GET", "/api/v1/defects/{{createdDefectId}}/comments", auth=False), 401, ["Response error.code is unauthorized."]),
    ]


def history_cases():
    return [
        case("HISTORY-API-001", "List defect history succeeds", "Verify defect history timeline is returned.", "High", ["User is authenticated.", "A defect exists with history events."], request("GET", "/api/v1/defects/{{createdDefectId}}/history"), 200, ["Response contains items array.", "History items contain eventType and createdAt."]),
        case("HISTORY-API-002", "History shows defect creation event", "Verify created defect has defect_created history event.", "High", ["User is authenticated.", "A defect was created by API."], request("GET", "/api/v1/defects/{{createdDefectId}}/history"), 200, ["At least one item has eventType defect_created."]),
        case("HISTORY-API-003", "History shows status change event", "Verify status update writes history event.", "High", ["User is authenticated.", "A defect status was updated."], request("GET", "/api/v1/defects/{{createdDefectId}}/history"), 200, ["At least one item has eventType status_changed."]),
        case("HISTORY-API-004", "History invalid defect returns not found", "Verify missing defect history request is rejected cleanly.", "Medium", AUTH, request("GET", "/api/v1/defects/{{missingDefectId}}/history"), 404, ["Response indicates defect not found."]),
        case("HISTORY-API-005", "History requires bearer token", "Verify history read is protected by bearer authentication.", "Critical", ["A defect exists."], request("GET", "/api/v1/defects/{{createdDefectId}}/history", auth=False), 401, ["Response error.code is unauthorized."]),
    ]


def dashboard_cases():
    return [
        case("DASH-API-001", "Dashboard summary succeeds", "Verify dashboard summary cards are returned.", "High", AUTH, request("GET", "/api/v1/dashboard/summary", headers={"X-Data-Context": "All"}), 200, ["Response contains totalDefects.", "Response contains status and severity metrics."]),
        case("DASH-API-002", "Dashboard summary respects Test context", "Verify summary is filtered to Test environments.", "High", AUTH, request("GET", "/api/v1/dashboard/summary", headers={"X-Data-Context": "Test"}), 200, ["Summary counts reflect Test context only."]),
        case("DASH-API-003", "Dashboard summary respects Prod context", "Verify summary is filtered to Prod environments.", "High", AUTH, request("GET", "/api/v1/dashboard/summary", headers={"X-Data-Context": "Prod"}), 200, ["Summary counts reflect Prod context only."]),
        case("DASH-API-004", "Dashboard summary filters active projects only", "Verify inactive projects are excluded from dashboard metrics.", "High", AUTH, request("GET", "/api/v1/dashboard/summary", headers={"X-Data-Context": "All"}), 200, ["Defects from inactive projects are excluded."]),
        case("DASH-API-005", "Dashboard charts succeeds", "Verify dashboard chart datasets are returned.", "High", AUTH, request("GET", "/api/v1/dashboard/charts", headers={"X-Data-Context": "All"}), 200, ["Response contains chart data collections."]),
        case("DASH-API-006", "Dashboard charts respect project filter", "Verify charts can be filtered by project.", "Medium", AUTH, request("GET", "/api/v1/dashboard/charts", query={"projectId": "{{data.projects.billingCore.id}}"}, headers={"X-Data-Context": "All"}), 200, ["Chart datasets reflect selected project."]),
        case("DASH-API-007", "Dashboard handles empty filter result", "Verify dashboard returns stable zero or empty datasets when filters match no records.", "Medium", AUTH, request("GET", "/api/v1/dashboard/charts", query={"projectId": "{{missingProjectId}}"}, headers={"X-Data-Context": "All"}), 200, ["Response is valid JSON.", "No server crash occurs."]),
        case("DASH-API-008", "Dashboard summary requires bearer token", "Verify dashboard summary cannot be read without authentication.", "Critical", [], request("GET", "/api/v1/dashboard/summary", auth=False), 401, ["Response error.code is unauthorized."]),
    ]


def renumber(cases, prefix):
    for index, item in enumerate(cases, 1):
        item["caseId"] = f"{prefix}-API-{index:03d}"
    return cases


def main():
    setup_files()
    modules = [
        ("auth.testcases.json", "Auth", auth_cases()),
        ("users.testcases.json", "Users", users_cases()),
        ("projects.testcases.json", "Projects", projects_cases()),
        ("environments.testcases.json", "Environments", environments_cases()),
        ("releases.testcases.json", "Releases", releases_cases()),
        ("workflow.testcases.json", "Workflow", workflow_cases()),
        ("defects.testcases.json", "Defects", defects_cases()),
        ("attachments.testcases.json", "Attachments", attachments_cases()),
        ("inline-assets.testcases.json", "Inline Assets", inline_cases()),
        ("comments.testcases.json", "Comments", comments_cases()),
        ("history.testcases.json", "History", history_cases()),
        ("dashboard.testcases.json", "Dashboard", dashboard_cases()),
    ]
    for filename, module, cases in modules:
        write(filename, module, cases)
    summary = {}
    for path in sorted(OUT.glob("*.testcases.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        summary[path.name] = len(data["testCases"])
    print(json.dumps(summary, indent=2))
    print("TOTAL", sum(summary.values()))


if __name__ == "__main__":
    main()
